# Task 10 Topics: Introduction to Numpy, Numpy Arrays


In [1]:
import numpy as np

In [2]:
my_arr = np.arange(100)

In [3]:
my_list = list(range(9))

In [4]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

Now let’s multiply each sequence by 2:

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 0.41706346, -0.37851758, -1.61236251],
       [-0.10842432, -0.46098604, -1.12043622]])

In [9]:
data*10

array([[  4.17063459,  -3.78517575, -16.12362511],
       [ -1.08424317,  -4.60986041, -11.20436217]])

In [10]:
data+data


array([[ 0.83412692, -0.75703515, -3.22472502],
       [-0.21684863, -0.92197208, -2.24087243]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Data Type

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [14]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [15]:
arr1.dtype
arr2.dtype

dtype('int32')

In [16]:
arr2.dtype


dtype('int32')

In [17]:
arr1.dtype

dtype('float64')

## Range

In [18]:
rng=np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Arthematic operation

In [20]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [21]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
arr**5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [26]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Basic Indexing and Slicing

In [27]:
arr = np.arange(10)

In [28]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[8]

8

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
arr_slice = arr[5:8]

In [33]:
arr_slice

array([5, 6, 7])

In [34]:
arr[5:8] = 12

In [37]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr_slice = arr[5:8]

In [36]:
arr_slice

array([12, 12, 12])

#                          End