# Topics: Broadcasting in Numpy Array


In [1]:
import numpy as np

In [2]:
'''Combining Scalar value with array'''
arr = np.arange(5)
print(arr)
arr = arr*5
arr

[0 1 2 3 4]


array([ 0,  5, 10, 15, 20])

In [3]:
'''De-meaning the array'''

arr = np.random.randn(4,3)
print(arr)
print()
arr.mean(0)  # Mean along axis 0
demean = arr - arr.mean(0)
print(demean)
print()

print(demean.mean(0))

[[ 0.22928142 -0.03137562  0.29037807]
 [-2.74359589  1.75694481 -1.56605989]
 [-2.25400337  0.2409645  -0.69023946]
 [ 0.38833506 -1.56962978  0.55561986]]

[[ 1.32427712 -0.1306016   0.64295343]
 [-1.64860019  1.65771883 -1.21348454]
 [-1.15900768  0.14173852 -0.33766411]
 [ 1.48333076 -1.66885575  0.90819522]]

[ 0.00000000e+00  5.55111512e-17 -5.55111512e-17]


In [5]:
'''Example 2'''

x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
y = np.array([1, 10, 100]).reshape(3, 1)

print(x + y)

[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


In [6]:
'''Example 3'''

x = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              [[9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]]])  # shape (2, 3, 3)
y = np.array([1, 10, 100])     # shape       (3,)

print(x + y)

[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]


In [7]:
arr = np.zeros((4,3))

arr[:] = 5

arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# #####################END